# Generated by Django 5.0.2 on 2024-10-12 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_admin_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_table',
            old_name='admin_pssword',
            new_name='admin_password',
        ),
    ]
